<?php
$routes = array(
  'default'           => 'Handler/error',
  'invalid'           => 'Handler/invalid',
  'matters'           => 'Matters',
  'minutes'           => 'Minutes',
  'minutes/download'  => 'Minutes/download',
  'members'           => 'Main',
  'attendances'       => 'Main',
  'notifications'     => 'Main',
  'matterlogs'        => 'Main',
  'matterstates'      => 'Main',
  'sections'          => 'Main',
  'sectionprivileges' => 'Main',
  'memos'             => 'Main',
  'membertypes'       => 'Main',
  'systemlogs'        => 'Main',
  'searchhistory'     => 'Main',
  'bypass'     => 'Main/bypass',
  'bypass'     => 'Main/bypass',
  'login'      => 'Main/login',
  'logout'      => 'Main/logout',
  '_test'             => '_Test',

  'matters/setstate'     => 'Matters/setState',
  'minutes/generate'     => 'Minutes/generate',
  'minutes/finalize'     => 'Minutes/finalize',
);
